### ISSUE TITLE
the module starts playing by itself

### ISSUE THREAD

**Issue by FuriousogreLabel** [react-player/reaplay#1]
the module when instaled start to play by itself and its imposible to set autoplay deactivated by default.

I tried with the example in codesandbox directly in my code, and does exactly the same effect. 
setIsPaying is false by two ticks and then it turns true byitself before even loads the song.

help

**Comment by Amir-Alipour** [comment]
hi, the codesandbox example is legacy version & it removed from readme,
use this example :
https://github.com/react-player/reaplay/blob/master/example/src/App.tsx

**Comment by Amir-Alipour** [comment]
**add this piece of code**

<img width="798" alt="Screenshot 2023-06-02 at 6 30 27 PM" src="https://github.com/react-player/reaplay/assets/73488911/9cedf5bb-ad7e-4488-aa03-29765826182b">
